
server:
  port: 8081
  
mars:
  bounds:
    min-x: 0
    max-x: 5
    min-y: 0
    max-y: 5
  initial-position:
    x: 1
    y: 1
    direction: N
  obstacles:
    list:
      -
        x: 2
        y: 2
      -
        x: 3
        y: 3